apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kibana
spec:
  selector:
    matchLabels:
      run: kibana
  template:
    metadata:
      labels:
        run: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.6.2
          env:
            - name: ELASTICSEARCH_URL
              value: http://elasticsearch:9200           
          ports:
            - containerPort: 5601
              name: http
              protocol: TCP